# Generated by Django 3.0.3 on 2020-03-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=80, verbose_name='Nome Popular')),
                ('nome_cientifico', models.CharField(max_length=80, verbose_name='Nome Científico')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='familias/')),
                ('referencia', models.CharField(max_length=80, verbose_name='Referência')),
            ],
        ),
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=80, verbose_name='Nome Popular')),
                ('nome_cientifico', models.CharField(max_length=80, verbose_name='Nome Científico')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('referencia', models.CharField(max_length=80, verbose_name='Referência')),
                ('imagem', models.ImageField(upload_to='arvores/')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Familia')),
            ],
        ),
    ]
