# Generated by Django 3.0.3 on 2020-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arvore',
            name='referencia',
            field=models.CharField(max_length=80, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='referencia',
            field=models.CharField(max_length=80, null=True, verbose_name='Referência'),
        ),
    ]
