# Generated by Django 3.0.3 on 2020-03-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200301_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arvore',
            name='imagem',
            field=models.ImageField(upload_to='media/arvores/'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='imagem',
            field=models.ImageField(upload_to='media/familias/'),
        ),
    ]
