# Generated by Django 3.0.3 on 2020-03-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200301_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arvore',
            name='imagem',
            field=models.ImageField(upload_to='arvores/'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='imagem',
            field=models.ImageField(upload_to='familias/'),
        ),
    ]
