# Generated by Django 3.0.3 on 2020-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200311_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('arquivo', models.ImageField(upload_to='producoes/')),
                ('data', models.DateField()),
            ],
        ),
    ]
