# Generated by Django 3.0.3 on 2020-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='arquivo',
            field=models.FileField(upload_to='producoes/'),
        ),
    ]
